### ISSUE TITLE
Overly-generic name in PYPI

### ISSUE THREAD

**Issue by swork** [hinnerk/py-tai64#10]
This package appears in PyPI under the name "tai64n" but is unusable with Python 3. An open pull request fixes the trivial problems that prevent using it with Python 3, but it remains unmerged for many months.

Please merge the pull request and republish the package in PyPI, or relinquish the name in PyPI so someone else can put up a Python 3 compatible package without resorting to a contorted name.

Thank you.

**Comment by hinnerk** [comment]
I've merged the changes, thanks for the hint.
